name: Release

on: 
  push:
    branches:
      - feature/test-slack-notify-step
    tags:
      - '!player/'
      - 'v*'

jobs:
  test_and_build:
    uses: ./.github/workflows/ci.yml

  download_and_publish:
    needs: test_and_build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: .

      - name: Unpackage artifact files
        run: tar -xzvf artifact/artifact.tar.gz -C .
        shell: bash

      - name: Publish
        run: echo Publish

      - name: Notify team
        run: node .github/scripts/notifySlackTeam.js 'success' 'CHANGELOG.md' '${{ fromJson(steps.define-release-version.outputs.result).full }}' ${{ secrets.RELEASE_SUCCESS_SLACK_WEBHOOK }}

  handle_failure:
    needs: [test_and_build, download_and_publish]
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.download_and_publish.result == 'failure' || needs.test_and_build.result == 'failure') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: feature/notify-team-on-release-workflow

      - name: Notify team
        run: node .github/scripts/notifySlackTeam.js 'failure' 'CHANGELOG.md' '' ${{ secrets.RELEASE_FAILURE_SLACK_WEBHOOK }} ${{ github.run_id }}